import { json, md } from "#/editor/editor-file-builders";
import type { EditorFileInput } from "#/editor/editor-files.types";

export const rootFiles: ReadonlyArray<EditorFileInput> = [
	{
		name: "README.md",
		folder: "~",
		language: "markdown",
		content: md(
			"# kirdes portfolio",
			"",
			"Terminal-first portfolio interface built with TanStack Start, React, and Tailwind CSS.",
			"",
			"Explore by navigating folders and opening files:",
			"",
			"- `ls` — list routes and files",
			"- `cd <route>` — navigate to a workspace view",
			"- `cat <file>` — print file contents",
			"- `open <file>` — open in read-only editor",
			"- `exit` — close editor",
		),
	},
	{
		name: "TODO.md",
		folder: "~",
		language: "markdown",
		content: md(
			"# TODO",
			"",
			"- [ ] get hired",
			"- [ ] being rich",
			"- [ ] learn to touch type properly (jk i'm fine)",
			"- [ ] fix all the bugs (or rename them features)",
			"- [ ] finally sort that one drawer at home",
			"- [ ] write a readme that's longer than the codebase",
			"- [ ] find the perfect coffee-to-code ratio",
			"- [ ] achieve inbox zero (impossible, next)",
		),
	},
	{
		name: "stack.json",
		folder: "~",
		language: "json",
		content: json({
			framework: "TanStack Start",
			runtime: "Cloudflare Workers",
			ui: ["React", "Tailwind CSS"],
			language: "TypeScript",
		}),
	},
	{
		name: "profile.ts",
		folder: "~",
		language: "typescript",
		content: md(
			"export const profile = {",
			'  name: "kirdes",',
			'  role: "product engineer / interface builder",',
			'  focus: ["frontend architecture", "design systems", "developer tooling"],',
			"} as const",
		),
	},
	{
		name: "infos.txt",
		folder: "~",
		language: "text",
		content: md(
			"LOCATION    Paris, France",
			"FOCUS       frontend architecture — design systems — dev tooling",
			"CONTACT     cedric@kirdes.dev / github.com/kirdesmf",
			"STATUS      open for freelance & collaboration",
		),
	},
	{
		name: "package.json",
		folder: "~",
		language: "json",
		content: json({
			name: "kirdes-portfolio",
			private: true,
			type: "module",
			scripts: {
				dev: "vite dev --port 3000",
				build: "vite build",
				preview: "vite preview",
				test: "vitest run",
				format: "biome format",
				lint: "biome lint",
				check: "biome check",
				typecheck: "tsc --noEmit",
				deploy: "bun run build && wrangler deploy",
			},
			dependencies: {
				"@base-ui/react": "^1.4.1",
				"@cloudflare/vite-plugin": "^1.36.4",
				"@tanstack/react-router": "^1.169.2",
				"@tanstack/react-start": "^1.167.65",
				animejs: "^4.4.1",
				cmdk: "^1.1.1",
				"lucide-react": "^0.545.0",
				react: "^19.2.6",
				"react-dom": "^19.2.6",
				shiki: "^4.0.2",
				tailwindcss: "^4.3.0",
				valibot: "^1.4.0",
				zustand: "^5.0.14",
			},
			devDependencies: {
				"@biomejs/biome": "2.4.5",
				"@types/react": "^19.2.14",
				"@types/react-dom": "^19.2.3",
				typescript: "^6.0.3",
				vite: "^8.0.12",
				vitest: "^4.1.6",
				wrangler: "^4.90.1",
			},
		}),
	},
];
