import { md } from "#/editor/editor-file-builders";
import type { EditorFileInput } from "#/editor/editor-files.types";

export const projectsFiles: ReadonlyArray<EditorFileInput> = [
	{
		name: "index.md",
		folder: "projects",
		language: "markdown",
		content: md(
			"# projects",
			"",
			"A small fake project index for the portfolio workspace.",
			"",
			"- [Atlas Notes](./atlas-notes.md) — local-first notes for research teams.",
			"- [Signal Forge](./signal-forge.md) — automation dashboard for product ops.",
			"- [Orbit UI](./orbit-ui.md) — design system playground for SaaS teams.",
		),
	},
	{
		name: "atlas-notes.md",
		folder: "projects",
		language: "markdown",
		content: md(
			"# Atlas Notes",
			"",
			"Atlas Notes is a fake local-first research notebook for small product teams.",
			"",
			"## highlights",
			"",
			"- offline-ready markdown workspace",
			"- backlink graph for project context",
			"- encrypted team sync prototype",
			"",
			"[← back to projects](./index.md)",
		),
	},
	{
		name: "signal-forge.md",
		folder: "projects",
		language: "markdown",
		content: md(
			"# Signal Forge",
			"",
			"Signal Forge is a fake product-ops dashboard for tracking launches and workflows.",
			"",
			"## highlights",
			"",
			"- rule-based automation builder",
			"- live status timeline",
			"- typed event stream viewer",
			"",
			"[← back to projects](./index.md)",
		),
	},
	{
		name: "orbit-ui.md",
		folder: "projects",
		language: "markdown",
		content: md(
			"# Orbit UI",
			"",
			"Orbit UI is a fake design-system playground for SaaS teams shipping fast.",
			"",
			"## highlights",
			"",
			"- token-driven component previews",
			"- theme comparison workspace",
			"- accessibility checklist flows",
			"",
			"[← back to projects](./index.md)",
		),
	},
];
