import { json, md } from "#/editor/editor-file-builders";
import type { EditorFileInput } from "#/editor/editor-files.types";

export const workFiles: ReadonlyArray<EditorFileInput> = [
	{
		name: "route.tsx",
		folder: "work",
		language: "tsx",
		content: md(
			'import { createFileRoute } from "@tanstack/react-router";',
			"",
			'export const Route = createFileRoute("/_browser/work")({',
			"\tcomponent: RouteComponent,",
			"});",
			"",
			"function RouteComponent() {",
			"\treturn (",
			"\t\t<section>",
			"\t\t\t<h1>work</h1>",
			"\t\t\t<p>selected projects and experience</p>",
			"\t\t</section>",
			"\t);",
			"}",
		),
	},
	{
		name: "experience.json",
		folder: "work",
		language: "json",
		content: json([
			{
				name: "kirdes",
				period: "2023 → now",
				role: "freelance product engineer",
			},
			{
				name: "indie",
				period: "2021 → now",
				role: "building tools and ui systems",
			},
		]),
	},
	{
		name: "freelance.md",
		folder: "work",
		language: "markdown",
		content: md(
			"# freelance",
			"",
			"Available for frontend architecture, design systems,",
			"and developer tooling projects.",
			"",
			"Contact via `/contact` or email cedric@kirdes.dev.",
		),
	},
	{
		name: "index.md",
		folder: "work/projects",
		language: "markdown",
		content: md(
			"# projects",
			"",
			"A small fake project index for the portfolio workspace.",
			"",
			"- [Atlas Notes](./atlas-notes.md) — local-first notes for research teams.",
			"- [Signal Forge](./signal-forge.md) — automation dashboard for product ops.",
			"- [Orbit UI](./orbit-ui.md) — design system playground for SaaS teams.",
		),
	},
	{
		name: "atlas-notes.md",
		folder: "work/projects",
		language: "markdown",
		content: md(
			"# Atlas Notes",
			"",
			"Atlas Notes is a fake local-first research notebook for small product teams.",
			"",
			"## highlights",
			"",
			"- offline-ready markdown workspace",
			"- backlink graph for project context",
			"- encrypted team sync prototype",
			"",
			"[← back to projects](./index.md)",
		),
	},
	{
		name: "signal-forge.md",
		folder: "work/projects",
		language: "markdown",
		content: md(
			"# Signal Forge",
			"",
			"Signal Forge is a fake product-ops dashboard for tracking launches and workflows.",
			"",
			"## highlights",
			"",
			"- rule-based automation builder",
			"- live status timeline",
			"- typed event stream viewer",
			"",
			"[← back to projects](./index.md)",
		),
	},
	{
		name: "orbit-ui.md",
		folder: "work/projects",
		language: "markdown",
		content: md(
			"# Orbit UI",
			"",
			"Orbit UI is a fake design-system playground for SaaS teams shipping fast.",
			"",
			"## highlights",
			"",
			"- token-driven component previews",
			"- theme comparison workspace",
			"- accessibility checklist flows",
			"",
			"[← back to projects](./index.md)",
		),
	},
];
