/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppWorkspaceRouteRouteImport } from './routes/_app/_workspace/route'
import { Route as AppWorkspaceWorksRouteRouteImport } from './routes/_app/_workspace/works/route'
import { Route as AppWorkspaceLabRouteRouteImport } from './routes/_app/_workspace/lab/route'
import { Route as AppWorkspaceWorksIndexRouteImport } from './routes/_app/_workspace/works/index'
import { Route as AppWorkspaceLabIndexRouteImport } from './routes/_app/_workspace/lab/index'
import { Route as AppWorkspaceWorksPortfolioOsRouteImport } from './routes/_app/_workspace/works/portfolio-os'
import { Route as AppWorkspaceLabSignalRoomRouteImport } from './routes/_app/_workspace/lab/signal-room'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceRouteRoute = AppWorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceWorksRouteRoute = AppWorkspaceWorksRouteRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceLabRouteRoute = AppWorkspaceLabRouteRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceWorksIndexRoute = AppWorkspaceWorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceWorksRouteRoute,
} as any)
const AppWorkspaceLabIndexRoute = AppWorkspaceLabIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceLabRouteRoute,
} as any)
const AppWorkspaceWorksPortfolioOsRoute =
  AppWorkspaceWorksPortfolioOsRouteImport.update({
    id: '/portfolio-os',
    path: '/portfolio-os',
    getParentRoute: () => AppWorkspaceWorksRouteRoute,
  } as any)
const AppWorkspaceLabSignalRoomRoute =
  AppWorkspaceLabSignalRoomRouteImport.update({
    id: '/signal-room',
    path: '/signal-room',
    getParentRoute: () => AppWorkspaceLabRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/home': typeof AppHomeRoute
  '/lab': typeof AppWorkspaceLabRouteRouteWithChildren
  '/works': typeof AppWorkspaceWorksRouteRouteWithChildren
  '/lab/signal-room': typeof AppWorkspaceLabSignalRoomRoute
  '/works/portfolio-os': typeof AppWorkspaceWorksPortfolioOsRoute
  '/lab/': typeof AppWorkspaceLabIndexRoute
  '/works/': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/home': typeof AppHomeRoute
  '/lab/signal-room': typeof AppWorkspaceLabSignalRoomRoute
  '/works/portfolio-os': typeof AppWorkspaceWorksPortfolioOsRoute
  '/lab': typeof AppWorkspaceLabIndexRoute
  '/works': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/loading': typeof LoadingRoute
  '/_app/_workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/_workspace/lab': typeof AppWorkspaceLabRouteRouteWithChildren
  '/_app/_workspace/works': typeof AppWorkspaceWorksRouteRouteWithChildren
  '/_app/_workspace/lab/signal-room': typeof AppWorkspaceLabSignalRoomRoute
  '/_app/_workspace/works/portfolio-os': typeof AppWorkspaceWorksPortfolioOsRoute
  '/_app/_workspace/lab/': typeof AppWorkspaceLabIndexRoute
  '/_app/_workspace/works/': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading'
    | '/home'
    | '/lab'
    | '/works'
    | '/lab/signal-room'
    | '/works/portfolio-os'
    | '/lab/'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loading'
    | '/home'
    | '/lab/signal-room'
    | '/works/portfolio-os'
    | '/lab'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/loading'
    | '/_app/_workspace'
    | '/_app/home'
    | '/_app/_workspace/lab'
    | '/_app/_workspace/works'
    | '/_app/_workspace/lab/signal-room'
    | '/_app/_workspace/works/portfolio-os'
    | '/_app/_workspace/lab/'
    | '/_app/_workspace/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoadingRoute: typeof LoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace': {
      id: '/_app/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace/works': {
      id: '/_app/_workspace/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof AppWorkspaceWorksRouteRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/lab': {
      id: '/_app/_workspace/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof AppWorkspaceLabRouteRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/works/': {
      id: '/_app/_workspace/works/'
      path: '/'
      fullPath: '/works/'
      preLoaderRoute: typeof AppWorkspaceWorksIndexRouteImport
      parentRoute: typeof AppWorkspaceWorksRouteRoute
    }
    '/_app/_workspace/lab/': {
      id: '/_app/_workspace/lab/'
      path: '/'
      fullPath: '/lab/'
      preLoaderRoute: typeof AppWorkspaceLabIndexRouteImport
      parentRoute: typeof AppWorkspaceLabRouteRoute
    }
    '/_app/_workspace/works/portfolio-os': {
      id: '/_app/_workspace/works/portfolio-os'
      path: '/portfolio-os'
      fullPath: '/works/portfolio-os'
      preLoaderRoute: typeof AppWorkspaceWorksPortfolioOsRouteImport
      parentRoute: typeof AppWorkspaceWorksRouteRoute
    }
    '/_app/_workspace/lab/signal-room': {
      id: '/_app/_workspace/lab/signal-room'
      path: '/signal-room'
      fullPath: '/lab/signal-room'
      preLoaderRoute: typeof AppWorkspaceLabSignalRoomRouteImport
      parentRoute: typeof AppWorkspaceLabRouteRoute
    }
  }
}

interface AppWorkspaceLabRouteRouteChildren {
  AppWorkspaceLabSignalRoomRoute: typeof AppWorkspaceLabSignalRoomRoute
  AppWorkspaceLabIndexRoute: typeof AppWorkspaceLabIndexRoute
}

const AppWorkspaceLabRouteRouteChildren: AppWorkspaceLabRouteRouteChildren = {
  AppWorkspaceLabSignalRoomRoute: AppWorkspaceLabSignalRoomRoute,
  AppWorkspaceLabIndexRoute: AppWorkspaceLabIndexRoute,
}

const AppWorkspaceLabRouteRouteWithChildren =
  AppWorkspaceLabRouteRoute._addFileChildren(AppWorkspaceLabRouteRouteChildren)

interface AppWorkspaceWorksRouteRouteChildren {
  AppWorkspaceWorksPortfolioOsRoute: typeof AppWorkspaceWorksPortfolioOsRoute
  AppWorkspaceWorksIndexRoute: typeof AppWorkspaceWorksIndexRoute
}

const AppWorkspaceWorksRouteRouteChildren: AppWorkspaceWorksRouteRouteChildren =
  {
    AppWorkspaceWorksPortfolioOsRoute: AppWorkspaceWorksPortfolioOsRoute,
    AppWorkspaceWorksIndexRoute: AppWorkspaceWorksIndexRoute,
  }

const AppWorkspaceWorksRouteRouteWithChildren =
  AppWorkspaceWorksRouteRoute._addFileChildren(
    AppWorkspaceWorksRouteRouteChildren,
  )

interface AppWorkspaceRouteRouteChildren {
  AppWorkspaceLabRouteRoute: typeof AppWorkspaceLabRouteRouteWithChildren
  AppWorkspaceWorksRouteRoute: typeof AppWorkspaceWorksRouteRouteWithChildren
}

const AppWorkspaceRouteRouteChildren: AppWorkspaceRouteRouteChildren = {
  AppWorkspaceLabRouteRoute: AppWorkspaceLabRouteRouteWithChildren,
  AppWorkspaceWorksRouteRoute: AppWorkspaceWorksRouteRouteWithChildren,
}

const AppWorkspaceRouteRouteWithChildren =
  AppWorkspaceRouteRoute._addFileChildren(AppWorkspaceRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceRouteRoute: typeof AppWorkspaceRouteRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceRouteRoute: AppWorkspaceRouteRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoadingRoute: LoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
