/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppWorkspaceRouteRouteImport } from './routes/_app/_workspace/route'
import { Route as AppWorkspaceRoadmapRouteImport } from './routes/_app/_workspace/roadmap'
import { Route as AppWorkspaceReadmeRouteImport } from './routes/_app/_workspace/readme'
import { Route as AppWorkspaceEditorRouteImport } from './routes/_app/_workspace/editor'
import { Route as AppWorkspaceContactRouteImport } from './routes/_app/_workspace/contact'
import { Route as AppWorkspaceAboutRouteImport } from './routes/_app/_workspace/about'
import { Route as AppWorkspaceWorksIndexRouteImport } from './routes/_app/_workspace/works/index'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceRouteRoute = AppWorkspaceRouteRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceRoadmapRoute = AppWorkspaceRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceReadmeRoute = AppWorkspaceReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceEditorRoute = AppWorkspaceEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceContactRoute = AppWorkspaceContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceAboutRoute = AppWorkspaceAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)
const AppWorkspaceWorksIndexRoute = AppWorkspaceWorksIndexRouteImport.update({
  id: '/works/',
  path: '/works/',
  getParentRoute: () => AppWorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/home': typeof AppHomeRoute
  '/about': typeof AppWorkspaceAboutRoute
  '/contact': typeof AppWorkspaceContactRoute
  '/editor': typeof AppWorkspaceEditorRoute
  '/readme': typeof AppWorkspaceReadmeRoute
  '/roadmap': typeof AppWorkspaceRoadmapRoute
  '/works/': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loading': typeof LoadingRoute
  '/home': typeof AppHomeRoute
  '/about': typeof AppWorkspaceAboutRoute
  '/contact': typeof AppWorkspaceContactRoute
  '/editor': typeof AppWorkspaceEditorRoute
  '/readme': typeof AppWorkspaceReadmeRoute
  '/roadmap': typeof AppWorkspaceRoadmapRoute
  '/works': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/loading': typeof LoadingRoute
  '/_app/_workspace': typeof AppWorkspaceRouteRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/_workspace/about': typeof AppWorkspaceAboutRoute
  '/_app/_workspace/contact': typeof AppWorkspaceContactRoute
  '/_app/_workspace/editor': typeof AppWorkspaceEditorRoute
  '/_app/_workspace/readme': typeof AppWorkspaceReadmeRoute
  '/_app/_workspace/roadmap': typeof AppWorkspaceRoadmapRoute
  '/_app/_workspace/works/': typeof AppWorkspaceWorksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading'
    | '/home'
    | '/about'
    | '/contact'
    | '/editor'
    | '/readme'
    | '/roadmap'
    | '/works/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loading'
    | '/home'
    | '/about'
    | '/contact'
    | '/editor'
    | '/readme'
    | '/roadmap'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/loading'
    | '/_app/_workspace'
    | '/_app/home'
    | '/_app/_workspace/about'
    | '/_app/_workspace/contact'
    | '/_app/_workspace/editor'
    | '/_app/_workspace/readme'
    | '/_app/_workspace/roadmap'
    | '/_app/_workspace/works/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoadingRoute: typeof LoadingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace': {
      id: '/_app/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppWorkspaceRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_workspace/roadmap': {
      id: '/_app/_workspace/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppWorkspaceRoadmapRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/readme': {
      id: '/_app/_workspace/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof AppWorkspaceReadmeRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/editor': {
      id: '/_app/_workspace/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppWorkspaceEditorRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/contact': {
      id: '/_app/_workspace/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppWorkspaceContactRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/about': {
      id: '/_app/_workspace/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppWorkspaceAboutRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
    '/_app/_workspace/works/': {
      id: '/_app/_workspace/works/'
      path: '/works'
      fullPath: '/works/'
      preLoaderRoute: typeof AppWorkspaceWorksIndexRouteImport
      parentRoute: typeof AppWorkspaceRouteRoute
    }
  }
}

interface AppWorkspaceRouteRouteChildren {
  AppWorkspaceAboutRoute: typeof AppWorkspaceAboutRoute
  AppWorkspaceContactRoute: typeof AppWorkspaceContactRoute
  AppWorkspaceEditorRoute: typeof AppWorkspaceEditorRoute
  AppWorkspaceReadmeRoute: typeof AppWorkspaceReadmeRoute
  AppWorkspaceRoadmapRoute: typeof AppWorkspaceRoadmapRoute
  AppWorkspaceWorksIndexRoute: typeof AppWorkspaceWorksIndexRoute
}

const AppWorkspaceRouteRouteChildren: AppWorkspaceRouteRouteChildren = {
  AppWorkspaceAboutRoute: AppWorkspaceAboutRoute,
  AppWorkspaceContactRoute: AppWorkspaceContactRoute,
  AppWorkspaceEditorRoute: AppWorkspaceEditorRoute,
  AppWorkspaceReadmeRoute: AppWorkspaceReadmeRoute,
  AppWorkspaceRoadmapRoute: AppWorkspaceRoadmapRoute,
  AppWorkspaceWorksIndexRoute: AppWorkspaceWorksIndexRoute,
}

const AppWorkspaceRouteRouteWithChildren =
  AppWorkspaceRouteRoute._addFileChildren(AppWorkspaceRouteRouteChildren)

interface AppRouteRouteChildren {
  AppWorkspaceRouteRoute: typeof AppWorkspaceRouteRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceRouteRoute: AppWorkspaceRouteRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoadingRoute: LoadingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
