/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteRouteImport } from './routes/terminal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalWorkRouteRouteImport } from './routes/terminal/work/route'
import { Route as TerminalContactRouteRouteImport } from './routes/terminal/contact/route'
import { Route as TerminalAboutRouteRouteImport } from './routes/terminal/about/route'
import { Route as TerminalWorkIndexRouteImport } from './routes/terminal/work/index'
import { Route as TerminalWorkProjectRouteRouteImport } from './routes/terminal/work/$project/route'

const TerminalRouteRoute = TerminalRouteRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalWorkRouteRoute = TerminalWorkRouteRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalContactRouteRoute = TerminalContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalAboutRouteRoute = TerminalAboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => TerminalRouteRoute,
} as any)
const TerminalWorkIndexRoute = TerminalWorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TerminalWorkRouteRoute,
} as any)
const TerminalWorkProjectRouteRoute =
  TerminalWorkProjectRouteRouteImport.update({
    id: '/$project',
    path: '/$project',
    getParentRoute: () => TerminalWorkRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRouteRouteWithChildren
  '/terminal/about': typeof TerminalAboutRouteRoute
  '/terminal/contact': typeof TerminalContactRouteRoute
  '/terminal/work': typeof TerminalWorkRouteRouteWithChildren
  '/terminal/work/$project': typeof TerminalWorkProjectRouteRoute
  '/terminal/work/': typeof TerminalWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRouteRouteWithChildren
  '/terminal/about': typeof TerminalAboutRouteRoute
  '/terminal/contact': typeof TerminalContactRouteRoute
  '/terminal/work/$project': typeof TerminalWorkProjectRouteRoute
  '/terminal/work': typeof TerminalWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/terminal': typeof TerminalRouteRouteWithChildren
  '/terminal/about': typeof TerminalAboutRouteRoute
  '/terminal/contact': typeof TerminalContactRouteRoute
  '/terminal/work': typeof TerminalWorkRouteRouteWithChildren
  '/terminal/work/$project': typeof TerminalWorkProjectRouteRoute
  '/terminal/work/': typeof TerminalWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terminal'
    | '/terminal/about'
    | '/terminal/contact'
    | '/terminal/work'
    | '/terminal/work/$project'
    | '/terminal/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terminal'
    | '/terminal/about'
    | '/terminal/contact'
    | '/terminal/work/$project'
    | '/terminal/work'
  id:
    | '__root__'
    | '/'
    | '/terminal'
    | '/terminal/about'
    | '/terminal/contact'
    | '/terminal/work'
    | '/terminal/work/$project'
    | '/terminal/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TerminalRouteRoute: typeof TerminalRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/work': {
      id: '/terminal/work'
      path: '/work'
      fullPath: '/terminal/work'
      preLoaderRoute: typeof TerminalWorkRouteRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/contact': {
      id: '/terminal/contact'
      path: '/contact'
      fullPath: '/terminal/contact'
      preLoaderRoute: typeof TerminalContactRouteRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/about': {
      id: '/terminal/about'
      path: '/about'
      fullPath: '/terminal/about'
      preLoaderRoute: typeof TerminalAboutRouteRouteImport
      parentRoute: typeof TerminalRouteRoute
    }
    '/terminal/work/': {
      id: '/terminal/work/'
      path: '/'
      fullPath: '/terminal/work/'
      preLoaderRoute: typeof TerminalWorkIndexRouteImport
      parentRoute: typeof TerminalWorkRouteRoute
    }
    '/terminal/work/$project': {
      id: '/terminal/work/$project'
      path: '/$project'
      fullPath: '/terminal/work/$project'
      preLoaderRoute: typeof TerminalWorkProjectRouteRouteImport
      parentRoute: typeof TerminalWorkRouteRoute
    }
  }
}

interface TerminalWorkRouteRouteChildren {
  TerminalWorkProjectRouteRoute: typeof TerminalWorkProjectRouteRoute
  TerminalWorkIndexRoute: typeof TerminalWorkIndexRoute
}

const TerminalWorkRouteRouteChildren: TerminalWorkRouteRouteChildren = {
  TerminalWorkProjectRouteRoute: TerminalWorkProjectRouteRoute,
  TerminalWorkIndexRoute: TerminalWorkIndexRoute,
}

const TerminalWorkRouteRouteWithChildren =
  TerminalWorkRouteRoute._addFileChildren(TerminalWorkRouteRouteChildren)

interface TerminalRouteRouteChildren {
  TerminalAboutRouteRoute: typeof TerminalAboutRouteRoute
  TerminalContactRouteRoute: typeof TerminalContactRouteRoute
  TerminalWorkRouteRoute: typeof TerminalWorkRouteRouteWithChildren
}

const TerminalRouteRouteChildren: TerminalRouteRouteChildren = {
  TerminalAboutRouteRoute: TerminalAboutRouteRoute,
  TerminalContactRouteRoute: TerminalContactRouteRoute,
  TerminalWorkRouteRoute: TerminalWorkRouteRouteWithChildren,
}

const TerminalRouteRouteWithChildren = TerminalRouteRoute._addFileChildren(
  TerminalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TerminalRouteRoute: TerminalRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
